---
- name: This is a sample for webserver setup
  hosts: "all"

  tasks:
  - name: Installing apache application
    apt:
      name: apache2
      state: present

  - name: Configuring a web page
    copy:
      content: "<h1>This is being built using Jenkins</h1>"
      dest: /var/www/html/index.html

  - name: Starting apache services
    service:
      name: apache2
      state: started
      enabled: true
